### ISSUE TITLE
Cannot build app-misc/tmsu-9999 anymore

### ISSUE THREAD

**Issue by ghost** [wichtounet/wichtounet-overlay#6]
Today I updated my Gentoo system and `app-misc/tmsu-9999` is the only package that cannot be built.

```
/usr/lib/go/bin/pkg/linux_amd64/github.com/hanwen/go-fuse/fuse.a(_go_.o): object is [linux amd64 go1.8.3 X:framepointer] expected [linux amd64 go1.9 ]
github.com/hanwen/go-fuse/fuse.(*DirEntryList).AddDirEntry: call to external function
github.com/hanwen/go-fuse/fuse.(*DirEntryList).AddDirLookupEntry: call to external function
github.com/hanwen/go-fuse/fuse.CurrentOwner: call to external function
github.com/hanwen/go-fuse/fuse.(*Server).DeleteNotify: call to external function
github.com/hanwen/go-fuse/fuse.(*Server).InodeNotify: call to external function
github.com/hanwen/go-fuse/fuse.(*Server).EntryNotify: call to external function
github.com/hanwen/go-fuse/fuse.FlagString: call to external function
github.com/hanwen/go-fuse/fuse.init: call to external function
github.com/hanwen/go-fuse/fuse.NewServer: call to external function
github.com/hanwen/go-fuse/fuse.(*Server).Unmount: call to external function
github.com/hanwen/go-fuse/fuse.(*Server).Serve: call to external function
type..hash.github.com/hanwen/go-fuse/fuse.DirEntry: call to external function
panic: runtime error: index out of range

goroutine 1 [running]:
cmd/link/internal/ld.decodetypeKind(...)
	/usr/lib/go/src/cmd/link/internal/ld/decodesym.go:68
cmd/link/internal/ld.newtype(0xc420510000, 0xc421728458, 0xc4215e3410)
	/usr/lib/go/src/cmd/link/internal/ld/dwarf.go:379 +0x300d
cmd/link/internal/ld.defgotype(0xc420510000, 0xc421728458, 0xc42178c905)
	/usr/lib/go/src/cmd/link/internal/ld/dwarf.go:374 +0x1d5
cmd/link/internal/ld.newtype(0xc420510000, 0xc421727e00, 0xc4224fa2c0)
	/usr/lib/go/src/cmd/link/internal/ld/dwarf.go:425 +0x28ca
cmd/link/internal/ld.defgotype(0xc420510000, 0xc421727e00, 0x3)
	/usr/lib/go/src/cmd/link/internal/ld/dwarf.go:374 +0x1d5
cmd/link/internal/ld.defdwsymb(0xc420510000, 0xc421727ee8, 0xc42178c930, 0x26, 0xc42295c544, 0x96520, 0xc421727e00)
	/usr/lib/go/src/cmd/link/internal/ld/dwarf.go:847 +0x19b
cmd/link/internal/ld.genasmsym(0xc420510000, 0x611138)
	/usr/lib/go/src/cmd/link/internal/ld/lib.go:1991 +0x3b8
cmd/link/internal/ld.dwarfgeneratedebugsyms(0xc420510000)
	/usr/lib/go/src/cmd/link/internal/ld/dwarf.go:1578 +0x6b4
cmd/link/internal/ld.(*Link).dodata(0xc420510000)
	/usr/lib/go/src/cmd/link/internal/ld/data.go:1844 +0x38e0
cmd/link/internal/ld.Main()
	/usr/lib/go/src/cmd/link/internal/ld/main.go:219 +0x9fe
main.main()
	/usr/lib/go/src/cmd/link/main.go:58 +0xac
make: *** [Makefile:34: compile] Error 2
```

Here you are my `emerge --info` output:

```
Portage 2.3.10 (python 3.6.1-final-0, default/linux/amd64/17.0/desktop/gnome/systemd, gcc-7.2.0, glibc-2.25-r5, 4.13.4-gnu x86_64)
=================================================================
System uname: Linux-4.13.4-gnu-x86_64-Intel-R-_Core-TM-2_Duo_CPU_E8400_@_3.00GHz-with-gentoo-2.4.1
KiB Mem:     8100036 total,    107820 free
KiB Swap:    8386556 total,   8386556 free
Timestamp of repository gentoo: Wed, 27 Sep 2017 18:43:54 +0000
Head commit of repository gentoo: 49b7da2eb28ec0ef21d5278f81dd22ee9f470fdb

Head commit of repository bitcoin: 3b01122791011e8eb22fe0a1c54ddf3953aa86a5

Timestamp of repository frabjous: Fri, 29 Sep 2017 12:06:44 +0000
Head commit of repository frabjous: 51f1ab19ad2b41aa43edce9a7814324171023a4f

Timestamp of repository gnome: Mon, 18 Sep 2017 08:06:59 +0000
Head commit of repository gnome: 9d57f801f6510c636c1353cf36dcc11f70df5c46

Timestamp of repository mozilla: Thu, 28 Sep 2017 21:52:26 +0000
Head commit of repository mozilla: b08e8f71e5a7fe9e2a2c894bdf89c65ca918555e

Timestamp of repository octopus: Fri, 29 Sep 2017 05:24:33 +0000
Head commit of repository octopus: 9855bce2034e86fa1a4dd74afa374fc8d7491106

Timestamp of repository qt: Tue, 26 Sep 2017 13:29:39 +0000
Head commit of repository qt: 25deed785d6d4d55321add769e5c842ab495f54b

Timestamp of repository wichtounet: Mon, 25 Sep 2017 07:09:20 +0000
Head commit of repository wichtounet: 70e33b3c35cc6b8136b7850c6ec623c68821a385

sh bash 4.4_p12
ld GNU ld (Gentoo 2.29.1 p1.0) 2.29.1
app-shells/bash:          4.4_p12::gentoo
dev-lang/perl:            5.24.3::gentoo
dev-lang/python:          2.7.14::gentoo, 3.5.4::gentoo, 3.6.1-r1::gentoo
dev-util/cmake:           3.9.3::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.4.1-r2::gentoo
sys-apps/sandbox:         2.10-r4::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69-r4::gentoo
sys-devel/automake:       1.15.1-r1::gentoo
sys-devel/binutils:       2.29.1::gentoo
sys-devel/gcc:            7.2.0::gentoo
sys-devel/gcc-config:     1.8-r1::gentoo
sys-devel/libtool:        2.4.6-r4::gentoo
sys-devel/make:           4.2.1-r1::gentoo
sys-kernel/linux-headers: 4.13::gentoo (virtual/os-headers)
sys-libs/glibc:           2.25-r5::gentoo
Repositories:

gentoo
    location: /var/portage/repos/gentoo
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/gentoo
    priority: -1000

bitcoin
    location: /var/portage/repos/bitcoin
    sync-type: git
    sync-uri: https://gitlab.com/bitcoin/gentoo
    masters: gentoo
    priority: 0

frabjous
    location: /var/portage/repos/frabjous
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/frabjous
    masters: gentoo
    priority: 0

gnome
    location: /var/portage/repos/gnome
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/gnome
    masters: gentoo
    priority: 0

mozilla
    location: /var/portage/repos/mozilla
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/mozilla
    masters: gentoo
    priority: 0

octopus
    location: /var/portage/repos/octopus
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/octopus
    masters: gentoo
    priority: 0

qt
    location: /var/portage/repos/qt
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/qt
    masters: gentoo
    priority: 0

wichtounet
    location: /var/portage/repos/wichtounet
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/wichtounet
    masters: gentoo
    priority: 0

fturco
    location: /var/portage/repos/fturco
    masters: gentoo
    priority: 1000

ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="@FREE"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -march=native -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/chromium/policies/managed/chrome-gnome-shell.json /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/opt/chrome/policies/managed/chrome-gnome-shell.json /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-O2 -march=native -pipe"
DISTDIR="/var/portage/distfiles"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs buildpkg config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync multilib-strict news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://mirror.switch.ch/ftp/mirror/gentoo/"
LANG="en_US.UTF-8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j2"
PKGDIR="/var/portage/packages"
PORTAGE_COMPRESS="xz"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X a52 aac acl acpi alsa amd64 audiofile bash-completion berkdb bidi bzip2 cairo cdda cdparanoia cdr clamav cli colord cracklib crypt css cups curl cxx dbus dri dts dvd dvdr eds emacs encode evo exif expat ffmpeg firefox flac fontconfig ftp gd gif gimp git glamor glut gmp gnome gnome-keyring gnome-online-accounts gnutls gphoto2 graphviz gstreamer gtk gzip hddtemp iconv icu ieee1394 imagemagick imap introspection ipv6 javascript jpeg lame latex lcms ldap libass libcaca libffi libnotify libsecret lm_sensors lua lzma lzo mad matroska mime modules mp3 mp4 mplayer mtp musicbrainz nautilus ncurses networkmanager nls nntp nptl odbc ogg openal opengl opus pam pango pch pcre pdf perl png policykit pulseaudio python qt3support qt5 readline rss ruby samba sasl scanner sdl seccomp session slang smp sndfile sound speex spell sqlite ssl startup-notification svg systemd taglib theora tiff tracker truetype udev udisks unicode upower usb v4l vala videos vnc vorbis webkit webp wifi x264 xcb xcomposite xft xinerama xml xmlrpc xv zlib" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2 sse3 sse4_1 ssse3" CURL_SSL="openssl" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="pc" INPUT_DEVICES="libinput" KERNEL="linux" L10N="en en-US" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LINGUAS="en en_US" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-6" POSTGRES_TARGETS="postgres9_5" PYTHON_SINGLE_TARGET="python3_6" PYTHON_TARGETS="python2_7 python3_5 python3_6" QEMU_SOFTMMU_TARGETS="x86_64 i386" RUBY_TARGETS="ruby23 ruby24" USERLAND="GNU" VIDEO_CARDS="intel i915 nouveau" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS
```

Please tell me if you need any other information.

**Comment by wichtounet** [comment]
Hi, 

Sorry about the delay and the issue. 

It seems that tmsu now has real release versions rather than only rolling-release. Moreover, it seems that sys-fs/tmsu has been integrate into portage directly. Can you try installing the last version from sys-fs/tmsu and tell if it's working correctly ? 

I will probably remove this package from the overlay since it does not seem necessary anymore. 

Thanks

**Comment by ghost** [comment]
`=sys-fs/tmsu-0.6.1::gentoo` works fine. Should I report the issue with the git version directly upstream perhaps?

**Comment by wichtounet** [comment]
Good :)

You may report the issue to https://github.com/oniony/TMSU, but it's also possible that they updated the way to build the library and I haven't updated correctly the ebuild.

Baptiste
